# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cumulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country_type', models.CharField(choices=[('CO', 'Country'), ('ST', 'State'), ('PR', 'Proposed')], default='PR', max_length=2)),
                ('capital_city', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('component_states', models.CharField(blank=True, max_length=1000, null=True)),
                ('total_area', models.IntegerField()),
                ('total_area_rank', models.IntegerField(blank=True, null=True)),
                ('total_area_closest', models.CharField(blank=True, max_length=100, null=True)),
                ('total_population', models.IntegerField()),
                ('total_population_rank', models.IntegerField(blank=True, null=True)),
                ('total_population_closest', models.CharField(blank=True, max_length=100, null=True)),
                ('population_density', models.DecimalField(decimal_places=2, max_digits=10)),
                ('population_density_rank', models.IntegerField(blank=True, null=True)),
                ('population_density_closest', models.CharField(blank=True, max_length=100, null=True)),
                ('gdp_total', models.IntegerField()),
                ('gdp_total_rank', models.IntegerField(blank=True, null=True)),
                ('gdp_total_closest', models.CharField(blank=True, max_length=100, null=True)),
                ('gdp_per_capita', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gdp_per_capita_rank', models.IntegerField(blank=True, null=True)),
                ('gdp_per_capita_closest', models.CharField(blank=True, max_length=100, null=True)),
                ('gini', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gini_rank', models.IntegerField(blank=True, null=True)),
                ('gini_closest', models.CharField(blank=True, max_length=100, null=True)),
                ('life_expectancy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('life_expectancy_rank', models.IntegerField(blank=True, null=True)),
                ('life_expectancy_closest', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
